name: quickbill_by_abdullah
description: QuickBill By Abdullah - Personal Invoicing App
publish_to: "none"

version: 1.1.2+7
environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.0
  printing: ^5.13.3
  pdf: ^3.11.0
  intl: ^0.19.0
  open_filex: ^4.4.0
  share_plus: ^10.1.2
  excel: ^4.0.3
  window_manager: ^0.3.8
  font_awesome_flutter: ^11.0.0
  file_picker: ^11.0.2
  fl_chart: ^1.1.1
  flutter_animate: ^4.5.2
  local_auth: ^2.3.0
  flutter_local_notifications: ^20.1.0
  tray_manager: ^0.5.2
  package_info_plus: ^8.0.2
  geolocator: ^13.0.2
  firebase_core: ^4.11.0
  firebase_messaging: ^16.4.1
  googleapis_auth: ^2.3.3
  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true

  assets:
    - assets/template.jpg
    - assets/icon.png
    - windows/runner/resources/app_icon.ico

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 700

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  windows:
    generate: true
    image_path: "assets/icon.png"
    icon_size: 48

